version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ventas
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ""
      PMA_USER: root
      PMA_PASSWORD: ""
      PMA_ARBITRARY: 0
    restart: always
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_web
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
